imgix.settings:
  type: config_object
  label: 'Imgix settings'
  mapping:
    settings:
      type: mapping
      mapping:
        enable:
          label: 'Enable Imgix Integration'
          type: boolean
        source_domain:
          label: 'Domain'
          type: string
        mapping_type:
          label: 'Type'
          type: string
        mapping_url:
          label: 'Base URL'
          type: string
        secure_url_token:
          label: 'Secure URL Token'
          type: string
        https:
          label: 'HTTPS support'
          type: boolean
