imgix.settings:
  type: config_object
  label: 'Imgix settings'
  mapping:
    settings:
      type: mapping
      mapping:
        enable:
          label: 'Enable Imgix Integration'
          type: boolean
        source_domain:
          label: 'Domain'
          type: string
        # 'webfolder' => 'Web Folder',
        # 'webproxy' => 'Web Proxy'
        # 's3' => 'Amazon S3'
        mapping_type:
          label: 'Type'
          type: string
        mapping_url:
          label: 'Base URL'
          type: string
        secure_url_token:
          label: 'Secure URL Token'
          type: string
        https:
          label: 'HTTPS support'
          type: boolean

imgix.presets:
  type: config_object
  label: 'Imgix presets'
  mapping:
    presets:
      type: sequence
      label: 'List of presets'
      sequence:
        type: mapping
        label: 'Preset'
        mapping:
          key:
            type: string
            label: 'The actual key'
          query:
            type: text
            label: 'The query string for this key'
